### ISSUE TITLE
Confirmação dados usuário para autenticação

### ISSUE THREAD

**Issue by oliveiralex** [sidneyrod/movieflix#1]
Olá Sidney, tudo bem?
Meu nome é Alexandre e estou corrigindo a sua atividade TAREFA: MovieFlix mobile. Executei o seu código e a tela de login está sendo renderizada certinha, no entanto, ao digitar os dados padrões de login (sendo user: bob@gmail.com / senha: 123456) está dando a mensagem indicando usuário ou senha inválidos.
Você poderia confirmar certinho os dados do usuário?

**Comment by sidneyrod** [comment]
Olá Alexandre! Tudo certo e vc?
Interessante que aqui local está rodando certinho quando entro com o usuário da 'ana@gmail.com' e do 'bob@gmail.com' conforme o data.sql do backend, pois o frontend buscou os mesmos dados.

Poderia conferir por favor se nos arquivos auth.ts e request.ts tem alguma inconsistência?

Obrigado!

**Comment by oliveiralex** [comment]
Oi Sidney, tudo bem?
Eu executei novamente e agora fui conferindo todos os passos, incluindo o seed do banco e funcionou perfeitamente. Muito obrigado!
E seu trabalho ficou muito bom, parabéns!

Abraço
Alexandre Oliveira
